// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxNdzeDLqID5lbW2jqdvKPPY-cmE8nHDQ',
    appId: '1:671699855598:web:b1392f9b7c1d22bb43abff',
    messagingSenderId: '671699855598',
    projectId: 'flutterfire-pmg-login',
    authDomain: 'flutterfire-pmg-login.firebaseapp.com',
    storageBucket: 'flutterfire-pmg-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WkZom2uVNSzcHE-NvsJIUrAMDfRfW2s',
    appId: '1:671699855598:android:b0d81d8acd32d49643abff',
    messagingSenderId: '671699855598',
    projectId: 'flutterfire-pmg-login',
    storageBucket: 'flutterfire-pmg-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHHckyaszjj_dpNDFBP50oTEUmW7uXW0',
    appId: '1:671699855598:ios:35c6e424bdc1788943abff',
    messagingSenderId: '671699855598',
    projectId: 'flutterfire-pmg-login',
    storageBucket: 'flutterfire-pmg-login.appspot.com',
    iosBundleId: 'com.example.loginappgoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHHckyaszjj_dpNDFBP50oTEUmW7uXW0',
    appId: '1:671699855598:ios:35c6e424bdc1788943abff',
    messagingSenderId: '671699855598',
    projectId: 'flutterfire-pmg-login',
    storageBucket: 'flutterfire-pmg-login.appspot.com',
    iosBundleId: 'com.example.loginappgoogle',
  );
}
